version: "3.5"
services:
    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: eventori
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data: